-- Arboles
INSERT INTO `planta` (`id_planta`, `nombre`, `stock`, `precio`, `descripcion`, `clasificacion`) VALUES (NULL, 'Mimosa', '10', '100000', 'Se trata de un árbol de entre 10-12 m de altura, perenne, usado en jardinería como ornamental, de crecimiento rápido pero raramente exceden de los 30 años de edad. De corteza grisácea o blanca y lisa, muy ramificado. Ramas angulosas, pubescentes. Hojas bipinnadas de 8-20, cada una de ellas con 25-40 pares de folíolos, con el haz glabro y el envés tomentoso. Inflorescencia en glomérulo globoso con más de 25 flores, muy olorosas. Pedúnculos pubescentes. Florece de enero a marzo. De cuatro a cinco semillas en una vaina verde-azulada, aplastada y un poco curvada. ', '3'); 
INSERT INTO `planta` (`id_planta`, `nombre`, `stock`, `precio`, `descripcion`, `clasificacion`) VALUES (NULL, 'Pino', '200', '10000', 'Pinus es un género de plantas vasculares, comúnmente llamadas pinos, pertenecientes al grupo de las coníferas y, dentro de este, a la familia de las Pinaceae, que presentan una ramificación frecuentemente verticilada y más o menos regular.', '3');
INSERT INTO `planta` (`id_planta`, `nombre`, `stock`, `precio`, `descripcion`, `clasificacion`) VALUES (NULL, 'Madroño', '300', '50000', 'El madroño es una especie de arbusto perteneciente al género Arbutus en la familia Ericaceae.', '3');
INSERT INTO `planta` (`id_planta`, `nombre`, `stock`, `precio`, `descripcion`, `clasificacion`) VALUES (NULL, 'Eucalipto', '900', '70000', 'Los eucaliptos o eucaliptas, Eucalyptus L\'Hér., es un género de árboles de la familia de las mirtáceas. Existen alrededor de setecientas especies, la mayoría oriundas de Australia y Nueva Guinea. En la actualidad, se encuentran distribuidos por gran parte del mundo.', '3'); 
INSERT INTO `planta` (`id_planta`, `nombre`, `stock`, `precio`, `descripcion`, `clasificacion`) VALUES (NULL, 'Ficus', '200', '1000000', 'El género Ficus contiene alrededor de 900 taxones específicos e infra-específicos aceptados de árboles, arbustos y trepadoras de la familia Moraceae, tribu monogenérica Ficeae, oriundas de la zona intertropical, con algunas de ellas distribuidas por las regiones templadas', '3'); 

-- Arbustos
INSERT INTO `planta` (`id_planta`, `nombre`, `stock`, `precio`, `descripcion`, `clasificacion`) VALUES (NULL, 'Camelia', '50', '10500', 'El género Camellia agrupa entre 100 y 250 especies originarias de las regiones tropicales y subtropicales de Asia sudoriental, China y Japón. Se las encuentra en los bosques situados a media altura sobre el nivel del mar.', '2'); 
INSERT INTO `planta` (`id_planta`, `nombre`, `stock`, `precio`, `descripcion`, `clasificacion`) VALUES (NULL, 'Grevillea', '20', '5000', 'Grevillea es un género con unas 370 especies aceptadas -aunque el APG eleva la cifra hasta 515​-, de las 550 descritas, ​ de plantas de flores pertenecientes a la familia Proteaceae, nativo esencialmente de Australia, con unas pocas especies en Papúa-Nueva Guinea y las islas al norte de Australia.​', '2'); 
INSERT INTO `planta` (`id_planta`, `nombre`, `stock`, `precio`, `descripcion`, `clasificacion`) VALUES (NULL, ' Jazmín del cabo ', '10', '4000', 'La Gardenia jasminoides, también conocida como jazmín del cabo, es un arbusto de hoja perenne que pertenece a la familia de las Rubiaceae. De origen asiático, estos arbustos con flor blanca perfumada cuenta con brillantes hojas verdes que remarcan aún más su espectacular floración. Apto para climas templados, requiere de humedad, luz solar pero que no incida de forma directa y abono rico en hierro ya que prefieren suelos ligeramente ácidos.', '2'); 
INSERT INTO `planta` (`id_planta`, `nombre`, `stock`, `precio`, `descripcion`, `clasificacion`) VALUES (NULL, 'Banderita española', '500', '200000', 'Este arbusto produce inflorescencias de varios colores, aunque también pueden presentar un único color como el amarillo o el rojo, e incluso el blanco. La Lantana camara es conocida de forma coloquial como lantana, banderita española, camará, ou i tomaca, confite, frutillo, supirrosa o cariaquito y pertenece a la familia Verbenaceae. Este arbusto es de tipo perennifolio, muy resistente y de rápido crecimiento. Además, se adapta sin dificultad a cualquier tipo de suelo siempre y cuando esté bien abonado.', '2'); 

-- Matorrales
INSERT INTO `planta` (`id_planta`, `nombre`, `stock`, `precio`, `descripcion`, `clasificacion`) VALUES (NULL, 'Matorral desértico', '50', '90000', 'El matorral desértico rosetófilo es un tipo de vegetación descrita por Rzedowski, presente en el ecosistema llamado matorral xerófilo, compuesto de plantas suculentas y generalmente espinosas;', '1'); 


SELECT `tipo`.`nombre_clasi`, COUNT(`tipo`.`nombre_clasi`) FROM `planta` join `tipo` on `planta`.`clasificacion` = `tipo`.`clasificacion` GROUP BY `tipo`.`nombre_clasi`; 